[package]
name = "rust-discord-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version="1.38.1", features=["full"] }

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity.git"
features = ["framework", "standard_framework"]